### ISSUE TITLE
it shows me some error  while i try to run in my system

### ISSUE THREAD

**Issue by Manickam-venkatachalam** [ccpu/join-images#6]
PS E:\nodejs\nodes> node imagescollage.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'E:\nodejs\nodes\imagescollage.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by zvictor** [comment]
can you please share the content of your `imagescollage.js`?

**Comment by ccpu** [comment]
Closing issue due to inactivity.
